# Generated by Django 3.0 on 2021-05-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210524_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('CA', 'client_admin'), ('VI', 'viewer')], default='VI', max_length=20, verbose_name='user role'),
        ),
    ]
