# Generated by Django 3.0 on 2021-05-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HdPlusSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_plus_number', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('longer_valid', models.DateField()),
                ('DTH_HD_Subscription', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=120)),
            ],
        ),
    ]
