# Generated by Django 3.0 on 2021-05-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HdRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_plus_number', models.CharField(max_length=120, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hdplussubscription',
            name='hd_plus_number',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
